# Generated by Django 3.1.2 on 2021-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('payment_info', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('screenshot', models.FileField(upload_to='')),
            ],
        ),
    ]
